### ISSUE TITLE
Reproducing experiments on your own images

### ISSUE THREAD

**Issue by leqo-c** [ruthcfong/perturb_explanations#1]
I was wondering if it were possible to replicate the experiments using my own images. How do I do that? Are there limitations on, for example, the size of the images?
Thank you very much

**Comment by ruthcfong** [comment]
@leqo-c sorry for the delayed reply. To replicate all the figures and experiments, follow the [figures ipython notebook](https://github.com/ruthcfong/perturb_explanations/blob/master/code/caffe/python/figures.ipynb). To run my method on any image, you can either call the [optimize_mask](https://github.com/ruthcfong/perturb_explanations/blob/master/code/caffe/python/optimize_mask.py#L108) function directly in [optimize_mask.py](https://github.com/ruthcfong/perturb_explanations/blob/master/code/caffe/python/optimize_mask.py#L108) or the [generate_splash_img](https://github.com/ruthcfong/perturb_explanations/blob/master/code/caffe/python/figures.py#L16) function in [figures.py](https://github.com/ruthcfong/perturb_explanations/blob/master/code/caffe/python/figures.py).

In the paper, we primarily visualize GoogLeNet; the [get_ILSVRC_net_transformer](https://github.com/ruthcfong/perturb_explanations/blob/master/code/caffe/python/helpers.py#L188) function in [helpers.py](https://github.com/ruthcfong/perturb_explanations/blob/master/code/caffe/python/helpers.py) takes a caffe Net model (i.e., GoogLeNet) and automatically crops it to the default size (i.e., 224 for GoogLeNet).

Let me know if you have any other questions.
